services:
  - type: web
    name: telegram-bot
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
